// tableData.js

import { formatProductDate } from "./TableComponent";


export const publishedColumns = [
  {
    accessorKey: "productId",
    header: "Product ID",
    cell: ({ getValue }) => getValue(),
  },
  {
    accessorKey: "productName",
    header: "Product Name",
    cell: ({ getValue }) => getValue(),
  },
  {
    accessorKey: "firstStock",
    header: "First Stock",
    cell: ({ getValue }) => getValue(),
  },
  {
    accessorKey: "sold",
    header: "Sold",
    cell: ({ getValue }) => getValue(),
  },
  {
    accessorKey: "dateAdded",
    header: "Date Added",
    cell: ({ getValue }) => <div className="text-xs px-1 text-slate-400 hover:text-slate-700 hover:p-10">{formatProductDate(getValue())}</div>,
  },
  {
    accessorKey: "pricing",
    header: "Pricing",
    cell: ({ getValue }) => getValue(),
  },
  {
    accessorKey: "supplier",
    header: "Supplier",
    cell: ({ getValue }) => getValue(),
  },
  {
    accessorKey: "lastOrderedDate",
    header: "Last Ordered Date",
    cell: ({ getValue }) => <div className="text-xs text-slate-400 hover:text-slate-700">{formatProductDate(getValue())}</div>,
  },
  {
    accessorKey: "rating",
    header: "Rating",
    cell: ({ getValue }) => (getValue() ? getValue() : "N/A"),
  },
];

export const publishedData = [
  {
    productId: "001",
    productName: "iPad Pro",
    firstStock: 100,
    sold: 80,
    dateAdded: "2023-01-15",
    pricing: "$999",
    supplier: "Apple Inc.",
    lastOrderedDate: "2024-05-10",
    rating: 4.5,
  },
  {
    productId: "002",
    productName: "iPhone 14",
    firstStock: 200,
    sold: 150,
    dateAdded: "2023-02-20",
    pricing: "$799",
    supplier: "Apple Inc.",
    lastOrderedDate: "2024-05-12",
    rating: 4.7,
  },
  {
    productId: "003",
    productName: "iMac",
    firstStock: 50,
    sold: 30,
    dateAdded: "2023-03-10",
    pricing: "$1299",
    supplier: "Apple Inc.",
    lastOrderedDate: "2024-05-15",
    rating: 4.8,
  },
  {
    productId: "004",
    productName: "MacBook Air",
    firstStock: 150,
    sold: 120,
    dateAdded: "2023-04-05",
    pricing: "$999",
    supplier: "Apple Inc.",
    lastOrderedDate: "2024-05-18",
    rating: 4.6,
  },
  {
    productId: "005",
    productName: "MacBook Pro",
    firstStock: 100,
    sold: 90,
    dateAdded: "2023-05-25",
    pricing: "$1999",
    supplier: "Apple Inc.",
    lastOrderedDate: "2024-05-20",
    rating: 4.9,
  },
  {
    productId: "006",
    productName: "iPad Air M2",
    firstStock: 100,
    sold: 80,
    dateAdded: "2023-01-15",
    pricing: "$799",
    supplier: "Apple Inc.",
    lastOrderedDate: "2024-05-10",
    rating: 4.5,
  },
  {
    productId: "007",
    productName: "iPhone 13 Mini",
    firstStock: 200,
    sold: 150,
    dateAdded: "2023-02-20",
    pricing: "$699",
    supplier: "Apple Inc.",
    lastOrderedDate: "2024-05-12",
    rating: 4.7,
  },
  {
    productId: "008",
    productName: 'iMac 24" M3',
    firstStock: 50,
    sold: 30,
    dateAdded: "2023-03-10",
    pricing: "$1499",
    supplier: "Apple Inc.",
    lastOrderedDate: "2024-05-15",
    rating: 4.8,
  },
  {
    productId: "009",
    productName: "MacBook Air M2",
    firstStock: 150,
    sold: 120,
    dateAdded: "2023-04-05",
    pricing: "$899",
    supplier: "Apple Inc.",
    lastOrderedDate: "2024-05-18",
    rating: 4.6,
  },
  {
    productId: "010",
    productName: 'MacBook Pro 13" M4',
    firstStock: 100,
    sold: 90,
    dateAdded: "2023-05-25",
    pricing: "$1999",
    supplier: "Apple Inc.",
    lastOrderedDate: "2024-05-20",
    rating: 4.9,
  },
];
export const draftData = [
  {
    productId: "011",
    productName: 'MacBook Air 13" M1',
    firstStock: 100,
    sold: 90,
    dateAdded: "2023-05-25",
    pricing: "$1999",
    supplier: "Apple Inc.",
    lastOrderedDate: "2024-05-20",
    rating: 4.9,
  },
];
