import React from "react";
import AuthHeader from "./_components/AuthHeader";
import SignUpPageOtherHalf from "./sign-up/_components/SignUpPageOtherHalf";
import SignUpStageIndicator from "./sign-up/_components/SignUpStageIndicator";
import { SignUpProvider } from "@/context/SignUpContext";
 
export const metadata: any = {
  title: "Einv | Create your account",
  description: "Generated by create next app",
};

const AuthLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <SignUpProvider>
        <div className="flex min-h-screen w-full flex-row">
          {/* add overflow-y-hidden */}
          <div className="flex w-full flex-row">
            <div className="flex h-full lg:w-1/2">
              <div className="mx-auto flex max-w-lg flex-col">
                {children}
                <SignUpStageIndicator outOf={3} />
              </div>
            </div>
            <div className="hidden lg:block lg:w-1/2">
              <SignUpPageOtherHalf />
            </div>
          </div>
        </div>
    </SignUpProvider>
  );
};

export default AuthLayout;
